#!/usr/bin/env python
#
# Opens the specified URL with Google Docs' PDF viewer.
# Copyright (C) 2010  Geoffrey Thomas <geofft@mit.edu>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import optparse
import subprocess
import os
import urllib

parser = optparse.OptionParser(usage="usage: %prog [options] <URL>")
parser.add_option("-e", "--embedded", action="store_true", dest="embedded",
                  help="Use the 'embedded' interface without a sidebar.")

def viewerurl(pdfurl, embedded=False):
    params = {'url': pdfurl, 'embedded': "true" if embedded else "false"}
    return "https://docs.google.com/viewer?" + urllib.urlencode(params)

def main():
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.error("no URL specified")

    browser = os.environ.get("BROWSER", "sensible-browser")
    subprocess.Popen([browser, viewerurl(args[0], options.embedded)])

if __name__=='__main__':
    main()
